<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>Nsp.Framework.Security</Title>
        <Authors>nextstarproject</Authors>
        <Description>Extract some cryptography for signing and verification, as well as encryption and decryption, jwt
sverification and signing.</Description>
        <Copyright>nextstarproject</Copyright>
        <PackageIcon>Resource\favicon.png</PackageIcon>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nsp.Framework.Core\Nsp.Framework.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.8.0" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.8.0" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Resource\favicon.png">
        <Pack>True</Pack>
        <PackagePath>/</PackagePath>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
